### PR TITLE
Adding --playlist-directory arg

### PR DESCRIPTION
**Pull request by Joniator**
Handle with care
Couldnt test it because im on windows, and I´m not really experienced with Python, so im not totally sure if I missed something important.

Reffering to issue #278

### CODE REVIEW

**Comment by Joniator** [comment]
K, nevermind, wouldnt work like this since I forgot about the relative paths.

**Comment by rygos** [comment]
Can you fix the issues instead of closing this pr? I want to have a function like this for Spotify Top 200 Weeklys and want to have a playlist for each but the files in the Directorys i setup with "format"

**Comment by Joniator** [comment]
I'm currently working on this, at least the problem with the absolute path is fixed, maybe I can push something today or tomorrow in a stable manner.

**Comment by Joniator** [comment]
I cant reopen this pr, bc I deleted the files multiple times in an attempt to properly sync my files with github (New to git on ubuntu, switched from windows to ubuntu more or less for this :sweat_smile:)

Iĺl update this in my other pr #280.

**Comment by jrnewell** [comment]
sorry, i have been busy this week.  I will try to find some time to look at this and merge it this weekend.  thank you for your help!

**Pull request closed without merging**
